name: crs
description: A car rental system.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get:
  hive:
  lottie:
  animations:
  hive_flutter:
  image_picker:
  google_fonts:
  firebase_core:
  supercharged:
  flutter_spinkit:
  carousel_slider:
  json_annotation:
  cupertino_icons:
  firebase_analytics:
  firebase_messaging:
  flutter_form_builder:
  cached_network_image:
  flutter_local_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints:
  hive_generator:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
